Add build scripts
telegraf/telegraf pull request #1191
Opened 2020-11-24 12:49 UTC by KnorpelSenf

# Description

Adds build scripts for convenient building of the library and the docs.

- `typecheck`: only checks the types of the library
- `build`: builds both lib and docs
- `build:lib`: builds the library
- `build:docs`: builds the docs
- `pretest`: make sure that the library typechecks and the docs can be built before running the tests
- `test`: runs the tests
- `lint`: lints the project
- `prepare`: npm hook that calls the build script both before `npm publish` and after `npm install`
- `clean`: remove generated files

2020-11-24 18:52 UTC, KnorpelSenf commented
@wojpawlik the conflicts are resolved.

You mentioned that checking the types of the example bots builds the library despite `noEmit` being set to true. Do you want this behaviour, and if not, can be even avoid it?

I'm fine with either option, so IMO can you merge this (unless you request changes).

2020-11-24 22:23 UTC, wojpawlik requested changes
I'd move `mjs-entry` to `prepare`, it should only fail when building does, so running it checks nothing.

`tsc` does less than and should be no faster than `tsc -b docs/examples/`

```json
"prepare": "npm run build && && mjs-entry src/index.ts > lib/index.mjs",
"build:lib": "tsc --build docs/examples/",
```

2020-11-25 12:36 UTC, wojpawlik requested changes

2020-11-25 12:36 UTC, wojpawlik commented on package.json
> +    "prepare": "npm run build && npm run build:docs && mjs-entry src/index.ts > lib/index.mjs",
Docs aren't necessary to use the lib
```suggestion
    "prepare": "npm run build && mjs-entry src/index.ts > lib/index.mjs",
```

2020-11-25 13:18 UTC, merged