fix #814
telegraf/telegraf pull request #1216
Opened 2020-12-06 12:51 UTC by septs

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Documentation (typos, code examples or any documentation update)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Node.js Version:
* Operating System:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2020-12-06 14:48 UTC, wojpawlik requested changes
Is `agent` required? Why?

2020-12-06 14:48 UTC, wojpawlik commented on src/core/network/client.ts
> +    })
I don't think it should create new `Agent` on every request...

2020-12-06 15:38 UTC, septs commented
> Is `agent` required? Why?

i not known

see https://github.com/telegraf/telegraf/commit/8fe5123e77383e04bba2dc6e2aff1f5ced613889
see https://github.com/telegraf/telegraf/commit/b96c59c4c12b1c02d5143a75d6d401c18130bc1c

2020-12-07 17:13 UTC, closed without merging

2020-12-08 09:24 UTC, KnorpelSenf commented
@sept Why closing? It's this fix not good?

2020-12-08 09:35 UTC, septs commented
https://t.me/TelegrafJSChat/12673

CC @KnorpelSenf

2020-12-08 09:45 UTC, KnorpelSenf commented
Thanks!

It's an issue if we split the communication between two platforms 😄 
Imagine how little people understand that aren't in the group chat … maybe we should provide those every time we take action based on discussions in the chat? @septs @wojpawlik

2020-12-08 10:34 UTC, wojpawlik commented
This fix is overly complex, I'll try something simpler first, it's my next priority