Add support for Telegram API v6.6 and v6.7
telegraf/telegraf pull request #1862
Opened 2023-07-20 05:38 UTC by hypernova7

@MKRhere please review this changes

2023-07-24 06:06 UTC, chakzefir commented
@hypernova how about to bump `answerInlineQuery`(https://core.telegram.org/bots/api#answerinlinequery) and add `button` param with TWA support?

2023-08-27 02:03 UTC, MKRhere commented
Seems like TypeScript dropped support for Node 12. Since it's been EOL since over a year ago, should we drop it from CI testing at least, to make things easier for ourselves?

2023-08-27 02:17 UTC, MKRhere commented
@chakzefir 

Did you mean this?
```TS
await ctx.answerInlineQuery([], { button: { text: "title", web_app: { url: "url" } } });
```

This currently works as per this PR.

I considered adding a button helper, but it does more harm than good:

```TS
await ctx.answerInlineQuery([], { button: Markup.button.inlineQueryResultsWebApp("title", { url: "url" }) });
```

I think we can leave this at that.

2023-08-27 02:25 UTC, MKRhere commented
So... Logical operators like `??=` only have support from Node 15. Node 14 is also EOL since 4 months ago, so I'm gonna cut it out of CI as well. We'll still fix bugs if someone reports issues with Node 14 until Telegraf v4.

2023-08-27 16:18 UTC, MKRhere requested changes

2023-08-27 16:18 UTC, MKRhere commented on src/telegram-types.ts
> +        message_thread_id?: number | undefined
Why was this necessary here? This type exists only to convert caption from `string` to `FmtString | string`.

2023-08-27 16:22 UTC, MKRhere commented on src/telegram-types.ts
> +        message_thread_id?: number | undefined
This type is only used in `editMessageMedia`, where `media` does not take `message_thread_id`, so this change is wrong; I'll remove it.

2023-08-27 16:25 UTC, MKRhere approved these changes

2023-08-27 17:34 UTC, MKRhere commented
I ended up adding API 6.8 support as well in this PR; feel free to review changes if you can.

2023-08-28 20:07 UTC, merged